### ISSUE TITLE
Atom Electron 9 development version: Cannot mix BigInt and other types

### ISSUE THREAD

**Issue by mfonville** [file-icons/atom-fs#10]
Trying the Atom Electron 9 development version ( https://github.com/atom/atom/pull/21777 ) it gives the following error.
Probably easy to fix, and would make this package ready for the upcoming Atom development update.

**Atom**: 1.56.0-dev-a241462b x64
**Electron**: 9.4.1
**OS**: Ubuntu 20.10
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.46

### Stack Trace

Failed to activate the file-icons package

```
At Cannot mix BigInt and other types, use explicit conversions

TypeError: Cannot mix BigInt and other types, use explicit conversions
    at BigIntStats._checkModeProperty (internal/fs/utils.js:364:21)
    at BigIntStats.StatsBase.isDirectory (internal/fs/utils.js:287:15)
    at FileSystem.resolveType (/packages/file-icons/node_modules/atom-fs/lib/filesystem.js:110:28)
    at FileSystem.get (/packages/file-icons/node_modules/atom-fs/lib/filesystem.js:69:13)
    at /packages/file-icons/lib/ui.js:34:29
    at Function.simpleDispatch (/usr/share/atom-dev/resources/app/static/<embedded>:11:1187699)
    at Emitter.emit (/usr/share/atom-dev/resources/app/static/<embedded>:11:1189140)
    at /packages/file-icons/lib/ui.js:61:19
    at Workspace.observeTextEditors (/usr/share/atom-dev/resources/app/static/<embedded>:11:428692)
    at UI.observe (/packages/file-icons/lib/ui.js:56:19)
    at Object.activate (/packages/file-icons/lib/main.js:14:11)
    at Package.activateNow (/usr/share/atom-dev/resources/app/static/<embedded>:11:3447088)
    at /usr/share/atom-dev/resources/app/static/<embedded>:11:3446500
    at Package.measure (/usr/share/atom-dev/resources/app/static/<embedded>:11:3444078)
    at /usr/share/atom-dev/resources/app/static/<embedded>:11:3446360
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom-dev/resources/app/static/<embedded>:11:3446303)
    at PackageManager.activatePackage (/usr/share/atom-dev/resources/app/static/<embedded>:11:382851)
    at /usr/share/atom-dev/resources/app/static/<embedded>:11:382467
    at Config.transactAsync (/usr/share/atom-dev/resources/app/static/<embedded>:11:331995)
    at PackageManager.activatePackages (/usr/share/atom-dev/resources/app/static/<embedded>:11:382417)
    at PackageManager.activate (/usr/share/atom-dev/resources/app/static/<embedded>:11:381967)
    at /usr/share/atom-dev/resources/app/static/<embedded>:1:719227
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (/usr/share/atom-dev/resources/app/static/<embedded>:1:719712)
```

### Non-Core Packages

```
busy-signal 2.0.1 
file-icons 2.1.46 
intentions 1.1.5 
language-debian 0.2.1 
language-protobuf 0.7.1 
linter 3.2.3 
linter-pylama 0.10.1 
linter-shellcheck 1.6.0 
linter-ui-default 2.4.1 
merge-conflicts 1.4.5 
project-manager 3.3.8 
tabs-to-spaces 1.0.5 
```

**Comment by Alhadis** [comment]
👋 Hey mate, thanks for pointing this out so early.

I've applied what I _hope_ will be a fix. Could you test [`7b3fa5aa`](https://github.com/file-icons/atom-fs/commit/7b3fa5aa53a9959a868287b3cebdf46920d6cfea.patch) locally? Something like this should work:

~~~console
$ cd ./packages/file-icons/node_modules/atom-fs
$ curl https://github.com/file-icons/atom-fs/commit/7b3fa5aa53a9959a868287b3cebdf46920d6cfea.patch | patch -p1
~~~

**Comment by mfonville** [comment]
I've applied the patch; but still receiving the error:

**Atom**: 1.56.0-dev-a241462b x64
**Electron**: 9.4.1
**OS**: Ubuntu 20.10
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.46


### Stack Trace

Failed to activate the file-icons package

```
At Cannot mix BigInt and other types, use explicit conversions

TypeError: Cannot mix BigInt and other types, use explicit conversions
    at BigIntStats._checkModeProperty (internal/fs/utils.js:364:21)
    at BigIntStats.StatsBase.isDirectory (internal/fs/utils.js:287:15)
    at FileSystem.resolveType (/packages/file-icons/node_modules/atom-fs/lib/filesystem.js:110:28)
    at FileSystem.get (/packages/file-icons/node_modules/atom-fs/lib/filesystem.js:69:13)
    at /packages/file-icons/lib/ui.js:34:29
    at Function.simpleDispatch (/usr/share/atom-dev/resources/app/static/<embedded>:11:1187699)
    at Emitter.emit (/usr/share/atom-dev/resources/app/static/<embedded>:11:1189140)
    at /packages/file-icons/lib/ui.js:61:19
    at Workspace.observeTextEditors (/usr/share/atom-dev/resources/app/static/<embedded>:11:428692)
    at UI.observe (/packages/file-icons/lib/ui.js:56:19)
    at Object.activate (/packages/file-icons/lib/main.js:14:11)
    at Package.activateNow (/usr/share/atom-dev/resources/app/static/<embedded>:11:3447088)
    at /usr/share/atom-dev/resources/app/static/<embedded>:11:3446500
    at Package.measure (/usr/share/atom-dev/resources/app/static/<embedded>:11:3444078)
    at /usr/share/atom-dev/resources/app/static/<embedded>:11:3446360
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom-dev/resources/app/static/<embedded>:11:3446303)
    at PackageManager.activatePackage (/usr/share/atom-dev/resources/app/static/<embedded>:11:382851)
    at /usr/share/atom-dev/resources/app/static/<embedded>:11:382467
    at Config.transactAsync (/usr/share/atom-dev/resources/app/static/<embedded>:11:331995)
    at PackageManager.activatePackages (/usr/share/atom-dev/resources/app/static/<embedded>:11:382417)
    at PackageManager.activate (/usr/share/atom-dev/resources/app/static/<embedded>:11:381967)
    at /usr/share/atom-dev/resources/app/static/<embedded>:1:719227
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (/usr/share/atom-dev/resources/app/static/<embedded>:1:719712)
```

### Non-Core Packages

```
busy-signal 2.0.1 
file-icons 2.1.46 
intentions 1.1.5 
language-debian 0.2.1 
language-protobuf 0.7.1 
linter 3.2.3 
linter-pylama 0.10.1 
linter-shellcheck 1.6.0 
linter-ui-default 2.4.1 
merge-conflicts 1.4.5 
project-manager 3.3.8 
tabs-to-spaces 1.0.5 
```

**Comment by mfonville** [comment]
If you want to do some debugging on your own machine; build artifacts of the Electron 9 PR are downloadable from https://github.visualstudio.com/Atom/_build/results?buildId=95698&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by mfonville** [comment]
Just wanted to let you know Atom with Electron 9 is now in beta: https://github.com/atom/atom/tree/1.56-releases

**Comment by claytonrcarter** [comment]
Just upgraded to Atom Beta 1.56 and starting getting this error. I know just enough atom/node to be dangerous to myself *and* to others, so please consider yourself warned:

I was able to "fix" this by hacking this line `stats.mode = BigInt(stats.mode);` into `resolveTypes` in `filesystem.js`. Which is to say I change the code at https://github.com/file-icons/atom-fs/blob/5ac74f40fee77164c4b846981cd18694a9f448c3/lib/filesystem.js#L110 to read:
```js
		stats.mode = BigInt(stats.mode);
		type.isDirectory = stats.isDirectory();
```

Clearly not a long term solution, but it was enough to get me back up and running.

**Comment by claytonrcarter** [comment]
Uh, make that "almost back up and running". I had to also do some BigInt hacking on lines 72 and 119... 

(The hack on line 110 got the editor to open, but these were needed for fuzzy finder to work.)

**Comment by Alhadis** [comment]
Sorry for the slow response. My phone picked the worst possible time to stop sending me push notifications from e-mails…

I'll cut a patch release of the package shortly so the fix I've applied will take place. Hopefully that's the last of our BigInt-related issues. 😞

Apologies for the noise, folks.

**Comment by claytonrcarter** [comment]
No worries! This seems to have fixed it for me. Thank you again for this!
