### ISSUE TITLE
Uncaught TypeError: this.master.getCurrentIcon is not a function

### ISSUE THREAD

**Issue by brunobord** [file-icons/Atom-FS#2]
Steps to reproduce:

1. Open Atom
2. see an ugly error message

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Ubuntu 16.04.5
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.27

### Stack Trace

Uncaught TypeError: this.master.getCurrentIcon is not a function

```
At /home/user/.atom/packages/file-icons/lib/service/icon-delegate.js:76

TypeError: this.master.getCurrentIcon is not a function
    at IconDelegate.getClasses (/packages/file-icons/lib/service/icon-delegate.js:76:18)
    at IconNode.refresh (/packages/file-icons/lib/service/icon-node.js:79:39)
    at IconNode.disposables.add.delegate.onDidChangeIcon (/packages/file-icons/lib/service/icon-node.js:33:40)
    at Function.simpleDispatch (/snap/atom/209/usr/share/atom/resources/app/static/<embedded>:11:1189948)
    at Emitter.emit (/snap/atom/209/usr/share/atom/resources/app/static/<embedded>:11:1191389)
    at IconDelegate.emitIconChange (/packages/file-icons/lib/service/icon-delegate.js:61:17)
    at IconDelegate.set (/packages/file-icons/lib/service/icon-delegate.js:318:12)
    at to.onDidChangeMaster.to (/packages/file-icons/lib/service/icon-delegate.js:307:48)
    at Function.simpleDispatch (/snap/atom/209/usr/share/atom/resources/app/static/<embedded>:11:1189948)
    at Emitter.emit (/snap/atom/209/usr/share/atom/resources/app/static/<embedded>:11:1191389)
    at IconDelegate.set (/packages/file-icons/lib/service/icon-delegate.js:315:21)
    at /packages/file-icons/lib/service/icon-delegate.js:324:15)
    at disposables.add.resource.onDidChangeRealPath (/packages/file-icons/lib/service/icon-service.js:73:18)
    at Function.simpleDispatch (/snap/atom/209/usr/share/atom/resources/app/static/<embedded>:11:1189948)
    at Emitter.emit (/snap/atom/209/usr/share/atom/resources/app/static/<embedded>:11:1191389)
    at Directory.emit (/packages/file-icons/node_modules/atom-fs/lib/resource.js:100:17)
    at Immediate.setImmediate (/packages/file-icons/node_modules/atom-fs/lib/resource.js:260:28)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

### Non-Core Packages

```
atom-jinja2 0.6.0 
blackboard-bb-ui 0.3.0 
busy-signal 2.0.0 
editorconfig 2.2.2 
file-icons 2.1.27 
file-watcher 2.0.0 
intentions 1.1.5 
jslint 1.5.1 
language-dot 1.7.0 
language-ini 1.20.0 
language-restructuredtext 1.1.2 
linter 2.2.0 
linter-flake8 2.3.0 
linter-markdown 5.2.2 
linter-ui-default 1.7.1 
markdown-lists 0.0.2 
markdown-mindmap 0.6.1 
markdown-table-formatter 2.9.2 
pretty-json 2.0.3 
sort-lines 0.18.0 
teletype 0.13.3 
```

**Comment by brunobord** [comment]
> Do you have any build scripts or filesystem watchers active in the workspace that may have caused this?

Not that I know of.

**Comment by Alhadis** [comment]
Alright, scratch that theory. Were you doing anything at all with symbolic links shortly before that error was triggered?

**Comment by brunobord** [comment]
Not at all. It happened after I upgraded from the Ubuntu PPA version to the snap on my Ubuntu.
It went from ``1.26.1-1~webupd8~0`` to ``1.33.1``.
At startup, the editor warned me there was an upgrade to perform on installed packages. I don't remember what was the previous ``file-icons`` version. I restarted the editor and now each time I'm launching Atom I have this nasty crash.

**Comment by brunobord** [comment]
Ok, so I've got good news and bad news.
The bad news is that it's getting a bit weirder and I hate when things are changing without a definite and logical reason.
The good news is that now that I've rebooted and relaunched atom, it doesn't throw the error anymore.

Shall we close this issue?

**Comment by Alhadis** [comment]
> The good news is that now that I've rebooted and relaunched atom, it doesn't throw the error anymore.

That's strange. Relaunching Atom should have been enough to clear any issues that've been known to persist from installing without restarting the editor.

As an aside, if you see weird stuff, the first thing you should do is [reset the package's in-memory cache](https://github.com/file-icons/atom#an-icon-has-stopped-updating). 

> The bad news is that it's getting a bit weirder and I hate when things are changing without a definite and logical reason.

This, on the other hand, is more concerning. Can you elaborate?

**Comment by brunobord** [comment]
> This, on the other hand, is more concerning. Can you elaborate?

Well, the problem solved itself, like magic. I hate magic in computing. There should be a logical explanation, here.
So, *"yay it's solved"*, but *"oh noes we don't know how it happened"*

**Comment by Alhadis** [comment]
You haven't explained what the problem *is*. What did you see, what was the file, and what icon(s) did you observe?

**Comment by brunobord** [comment]
> You haven't explained what the problem is. What did you see, what was the file, and what icon(s) did you observe?

erm... the problem was the error thrown, wasn't it? :o)

**Comment by Alhadis** [comment]
No, I'm now referring to this:

> it's getting a bit weirder and I hate when things are changing without a definite and logical reason.

What do you mean by "getting weirder"? What's "changing without a definite or logical reason"?

**Comment by brunobord** [comment]
> What do you mean by "getting weirder"? What's "changing without a definite or logical reason"?

Oh, I'm sorry my sentence was confusing. I'll try to be a bit clearer: *the fact that the error has disappeared* **is** the weird event to me.
Is it clearer now?

**Comment by Alhadis** [comment]
Okay, yes. Thank you, that made it sound like there were two issues here.

I'm not 100% sure what happened either, but if it happens again, please open a new issue.

**Comment by brunobord** [comment]
gotcha! thank you for your time.
